### ISSUE TITLE
Evaluation phase of Mining Invariants is completely wrong.

### ISSUE THREAD

**Issue by bennyguo** [logpai/loglizer#13]
line 265 of `models/mining_invariants.py`:
```{python}
for key in invar_dict:
	valid_col_list.append(list(key))
	valid_invar_list.append(list(invar_dict[key]))
```
Please notice that `set` is an unordered data structure. You use `frozenset` to index the dict, but transforming the `frozenset` object to `list` will bring unexpected mismatch between column number and theta value.

Due to the implementation error, I believe the algorithm performance reported in your paper is not convincing.

**Comment by ShilinHe** [comment]
Hi, Thank you for pointing it out. 
Converting "frozenset" to "list" could change the order in some cases. After inspecting the value of invari_dict, valid_col_list, and valid_invar_list, we find that they are exactly the same, which shows that this converting does not change the value with our data (maybe because that these variables are sorted integers). 

But it is true that frozenset is not a good practice and may lead to some problems. Therefore, we change the frozenset to tuple when storing it to the dictionary. **Based on this modification, we re-do some experiments on our datasets. The experimental results are exactly the same as before.**  We think that the break of any invariant could yeild an anomaly, and log events are strongly related internally. Therefore, the failure of some invariants (not all) can indicate an anomaly.

If you find any problem, please contact us. 
Really appreciate your help!

**Comment by jimzhu** [comment]
We have updated our demo code recently for readability. Pls try the new demos. @bennyguo
